# This is a basic workflow to help you get started with Actions

name: workflow_everyday

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
   - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install chromium-chromedriver
        sudo chmod -R 777 .
    - name: Run Script
      run: python whisky_crawler.py --loja "casadabebida"
    - name: Commit Files
      run: |
        git config --global user.name 'Roberto Silveira Bot'
        git config --global user.email 'rsilveira79@gmail.com'
        git commit -am "Automated report - updating data files: output"
        git push
